import type { Evidence, Theory } from './types';

export const MOCK_THEORIES: Theory[] = [
  {
    id: 'mkultra',
    title: 'MKUltra — CIA mind-control experiments on unwitting subjects',
    summary:
      'Declassified Senate hearings (1977) and FOIA-released documents confirm a 20-year CIA program testing LSD, hypnosis, and behavioural conditioning on civilians, prisoners, and military personnel without consent.',
    category: 'military-intelligence',
    score: 9,
    evidenceCount: 12,
    independentSources: 6,
    youtubeId: 'dsoZvQd8REw',
    status: 'accepted',
    submittedBy: 'archivist_42',
    submittedAt: '2026-04-21T09:11:00Z',
  },
  {
    id: 'cointelpro',
    title: 'COINTELPRO surveillance and disruption of US political movements',
    summary:
      'FBI internal memos (Church Committee, 1976) document covert operations to infiltrate, discredit, and disrupt civil-rights, anti-war, and labour groups between 1956 and 1971.',
    category: 'surveillance-privacy',
    score: 8,
    evidenceCount: 9,
    independentSources: 5,
    youtubeId: 'GMWuJipChs0',
    status: 'accepted',
    submittedBy: 'libertas',
    submittedAt: '2026-04-19T14:32:00Z',
  },
  {
    id: 'tuskegee',
    title: 'Tuskegee Syphilis Study — 40 years of untreated disease in Black men',
    summary:
      'US Public Health Service withheld penicillin from 399 Black sharecroppers between 1932 and 1972 to observe untreated syphilis. Confirmed by 1973 Ad Hoc Advisory Panel report and 1997 presidential apology.',
    category: 'health-medicine',
    score: 9,
    evidenceCount: 14,
    independentSources: 7,
    youtubeId: 'FvHrSqdZwBE',
    status: 'accepted',
    submittedBy: 'public_health_md',
    submittedAt: '2026-04-15T18:05:00Z',
  },
  {
    id: 'nsa-prism',
    title: 'NSA PRISM — bulk collection of US communications metadata',
    summary:
      'Snowden disclosures (2013) and subsequent Privacy and Civil Liberties Oversight Board reports confirm the NSA collected metadata on essentially all US phone calls under Section 215.',
    category: 'surveillance-privacy',
    score: 9,
    evidenceCount: 18,
    independentSources: 8,
    youtubeId: 'kaUemcqIQ-k',
    status: 'accepted',
    submittedBy: 'cypher',
    submittedAt: '2026-04-11T07:45:00Z',
  },
  {
    id: 'operation-mockingbird',
    title: 'Operation Mockingbird — CIA cultivation of US journalists',
    summary:
      'Church Committee (1975) and Carl Bernstein’s Rolling Stone reporting (1977) document a CIA program that placed agency assets in major US news outlets during the Cold War.',
    category: 'media-propaganda',
    score: 7,
    evidenceCount: 8,
    independentSources: 4,
    youtubeId: 'lQLRgnspAyk',
    status: 'accepted',
    submittedBy: 'fourth_estate',
    submittedAt: '2026-04-08T10:21:00Z',
  },
  {
    id: 'gulf-of-tonkin',
    title: 'Gulf of Tonkin — second attack used to justify Vietnam escalation never happened',
    summary:
      'NSA historian Robert Hanyok’s 2001 internal study (declassified 2005) concluded the 4 August 1964 second attack on USS Maddox was a misreading of signals intelligence; no North Vietnamese vessels were present.',
    category: 'military-intelligence',
    score: 8,
    evidenceCount: 7,
    independentSources: 4,
    youtubeId: 'KmKE7ZDnsY8',
    status: 'accepted',
    submittedBy: 'historica',
    submittedAt: '2026-04-04T16:09:00Z',
  },
  {
    id: 'big-tobacco',
    title: 'Tobacco industry concealed knowledge of cancer link for decades',
    summary:
      'Internal industry documents released through the Master Settlement Agreement (1998) show executives knew of nicotine addictiveness and lung-cancer association from the 1950s while publicly denying both.',
    category: 'pharma-vaccines',
    score: 9,
    evidenceCount: 22,
    independentSources: 9,
    youtubeId: '1_-Vu8LrUDk',
    status: 'accepted',
    submittedBy: 'whistle',
    submittedAt: '2026-03-30T12:00:00Z',
  },
  {
    id: 'lab-leak',
    title: 'SARS-CoV-2 originated from a research-related incident in Wuhan',
    summary:
      'US ODNI assessment (2023) and FBI/DOE leaning toward lab-origin hypothesis with low-to-moderate confidence; other agencies favour zoonotic origin. Direct evidence remains classified or restricted.',
    category: 'health-medicine',
    score: 5,
    evidenceCount: 11,
    independentSources: 4,
    youtubeId: 'zzbcG7CRYgQ',
    status: 'accepted',
    submittedBy: 'biosafety_l4',
    submittedAt: '2026-03-25T08:14:00Z',
  },
  {
    id: 'flat-earth',
    title: 'The Earth is flat',
    summary:
      'Contradicted by gravity, satellite imagery, circumnavigation, lunar eclipses, time-zone behaviour, GPS, and direct ISS observation. No reproducible evidence supports a flat geometry.',
    category: 'science-technology',
    score: 1,
    evidenceCount: 4,
    independentSources: 1,
    youtubeId: 'VNqNnUJVcVs',
    status: 'accepted',
    submittedBy: 'skeptic',
    submittedAt: '2026-03-22T19:42:00Z',
  },
  {
    id: 'moon-landing-fake',
    title: 'The Apollo 11 moon landing was filmed on a soundstage',
    summary:
      'Refuted by retroreflectors used by independent observatories worldwide, returned lunar samples studied by non-US labs, and Soviet tracking data confirming the mission.',
    category: 'astronomy-space',
    score: 2,
    evidenceCount: 6,
    independentSources: 2,
    youtubeId: 'Im5GmX6Emn4',
    status: 'accepted',
    submittedBy: 'apollo_archive',
    submittedAt: '2026-03-18T11:30:00Z',
  },
  {
    id: 'bilderberg',
    title: 'Bilderberg meetings shape global policy outside democratic oversight',
    summary:
      'Annual private meetings of ~130 political and business leaders since 1954 are documented. Direct evidence of binding policy decisions versus informal consensus-building remains contested.',
    category: 'secret-societies',
    score: 5,
    evidenceCount: 6,
    independentSources: 3,
    youtubeId: 'Bd30Jc4Qudo',
    status: 'accepted',
    submittedBy: 'transparency_now',
    submittedAt: '2026-03-12T15:55:00Z',
  },
  {
    id: 'roswell',
    title: 'A non-human craft was recovered near Roswell in July 1947',
    summary:
      'US Air Force Project Mogul (1994 report) attributes the debris to a high-altitude balloon array. Witness statements collected decades later differ; physical evidence chain-of-custody is incomplete.',
    category: 'ufo-extraterrestrial',
    score: 4,
    evidenceCount: 5,
    independentSources: 2,
    youtubeId: 'RCAHyclAmZs',
    status: 'accepted',
    submittedBy: 'desert_eyes',
    submittedAt: '2026-03-08T22:18:00Z',
  },
];

export const MOCK_EVIDENCE: Record<string, Evidence[]> = {
  mkultra: [
    {
      id: 'ev-mkultra-1',
      theoryId: 'mkultra',
      type: 'government-document',
      title: 'Senate Select Committee — “Project MKUltra” hearing transcript',
      source: 'US Senate, 95th Congress',
      url: 'https://www.intelligence.senate.gov/sites/default/files/hearings/95mkultra.pdf',
      description:
        'Joint Senate hearing on 3 August 1977 documenting the program’s scope, including testing on civilians and prisoners.',
      score: 5,
      stance: 'supporting',
      submittedBy: 'archivist_42',
      submittedAt: '2026-04-21T09:11:00Z',
    },
    {
      id: 'ev-mkultra-2',
      theoryId: 'mkultra',
      type: 'declassified-military',
      title: 'CIA Subproject files released under FOIA',
      source: 'CIA Reading Room',
      url: 'https://www.cia.gov/readingroom/collection/mkultra-mind-control-cia',
      description:
        '~20,000 pages of MKUltra subproject memos surviving the 1973 destruction order.',
      score: 4,
      stance: 'supporting',
      submittedBy: 'archivist_42',
      submittedAt: '2026-04-21T09:11:00Z',
    },
    {
      id: 'ev-mkultra-3',
      theoryId: 'mkultra',
      type: 'peer-reviewed-paper',
      title: 'Marks, J. — “The Search for the Manchurian Candidate”',
      source: 'Times Books, 1979',
      url: 'https://archive.org/details/searchformanchur00mark',
      description:
        'Investigative monograph reconstructed from declassified files; cited extensively in subsequent scholarship.',
      score: 4,
      stance: 'supporting',
      submittedBy: 'historica',
      submittedAt: '2026-04-22T10:00:00Z',
    },
  ],
  'flat-earth': [
    {
      id: 'ev-flat-1',
      theoryId: 'flat-earth',
      type: 'reproducible-experiment',
      title: 'Eratosthenes shadow experiment — reproducible globally',
      source: 'Independent classroom replications',
      url: 'https://en.wikipedia.org/wiki/Eratosthenes',
      description:
        'Simultaneous shadow-angle measurements at distant latitudes consistently yield Earth circumference ≈ 40,000 km.',
      score: 1,
      stance: 'contradicting',
      submittedBy: 'skeptic',
      submittedAt: '2026-03-22T19:42:00Z',
    },
    {
      id: 'ev-flat-2',
      theoryId: 'flat-earth',
      type: 'verified-image',
      title: 'ISS continuous live feed — visible curvature',
      source: 'NASA HDEV / Live ISS Stream',
      url: 'https://eol.jsc.nasa.gov/',
      description:
        'Continuous independent observation since 2014 shows curved horizon and rotation consistent with an oblate spheroid.',
      score: 2,
      stance: 'contradicting',
      submittedBy: 'skeptic',
      submittedAt: '2026-03-22T19:42:00Z',
    },
  ],
  'lab-leak': [
    {
      id: 'ev-lableak-1',
      theoryId: 'lab-leak',
      type: 'government-document',
      title: 'ODNI Declassified Assessment on COVID-19 Origins',
      source: 'US Office of the Director of National Intelligence (2023)',
      url: 'https://www.dni.gov/files/ODNI/documents/assessments/Declassified-Assessment-on-COVID-19-Origins.pdf',
      description:
        'Multiple agencies split between zoonotic and lab-related origin; no consensus, low-to-moderate confidence on either.',
      score: 3,
      stance: 'supporting',
      submittedBy: 'biosafety_l4',
      submittedAt: '2026-03-25T08:14:00Z',
    },
    {
      id: 'ev-lableak-2',
      theoryId: 'lab-leak',
      type: 'witness-without-risk',
      title: 'Senate HSGAC interim staff report',
      source: 'US Senate Homeland Security Committee',
      url: 'https://www.hsgac.senate.gov/',
      description:
        'Interim staff report concluding lab-related incident is more likely than zoonotic spillover; criticised for selective sourcing.',
      score: 3,
      stance: 'supporting',
      submittedBy: 'public_health_md',
      submittedAt: '2026-03-26T08:14:00Z',
    },
  ],
};

export function getEvidenceFor(theoryId: string): Evidence[] {
  return MOCK_EVIDENCE[theoryId] ?? [];
}
